require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses

Style/MethodDefParentheses:
  Enabled: true
  EnforcedStyle: require_no_parentheses

Style/SignalException:
  Enabled: true
  EnforcedStyle: semantic

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SuperWithArgsParentheses:
  Enabled: false

Layout/LineLength:
  Max: 120
